language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js: node
before_install:
- npm i -g npm5@latest
script:
- npm run lint
- make dist
after_success:
#- npm run semantic-release
- cd dist
- git init
- git config user.name "Travis CI"
- git config user.email "github@coderbyheart.com"
- git add .
- git commit -m "Deploy to GitHub Pages"
- git push --force --quiet "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" master:gh-pages > /dev/null 2>&1
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
